services:
  - type: web
    name: btc-signal-bot-v3
    env: python
    region: frankfurt          # EU Central — Binance NOT geoblocked here
    plan: free
    buildCommand: pip install ccxt pandas numpy ta requests scikit-learn
    startCommand: python -u btc_apex_v5.py
    autoDeploy: true
    envVars:
      - key: TG_TOKEN
        value: 8775276870:AAGABvQ6PwtRgGPNbk3V4YX_A0eVXxpiWyo
      - key: TG_CHAT
        value: "998659643"
      - key: PORT
        value: "10000"
