services:
  - type: web
    name: btc-signal-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -u btc_audited.py
    envVars:
      - key: TG_TOKEN
        value: 8775276870:AAGABvQ6PwtRgGPNbk3V4YX_A0eVXxpiWyo
      - key: TG_CHAT
        value: "998659643"
